config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [ :new ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :blog, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles
    validates :first_name, presence: true, length: { minimum: 3 }
    validates :last_name, presence: true, length: { minimum: 3 }
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 105 }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [ :show, :edit, :update, :destroy ]

    def show
    end

    def index
        @articles = Article.all
    end
    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.last
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
             render "new"
        end
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
             render "edit"
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, :blog)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @articles = @user.articles
    end

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
           flash[:notice] = "Your account was updated successfully"
           redirect_to root_path
        else
            render "new"
        end
    end


    def create
        @user = User.new(user_params)
        if @user.save
           flash[:notice] = "Welcome to the Alpha Blog, your account was created successfully"
           redirect_to root_path
        else
            render "new"
        end
    end
    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div class="card text-center my-3">
    <div class="card-header" id="head_foot">
    <i  class="text-white">by <%= article.user.first_name %>  <%= article.user.last_name %></i>
    </div>
    <div class="card-body px-5 card_bg text-black px-auto">
      <h5 class="card-title"> <%= link_to article.title.titlecase, article_path(article),  class: "title_link" %></h5>
      <p class="card-text"><%= simple_format(article.description)%></p>
      <%= link_to "Show", article_path(article), class: "actions_go" %>
      <%= link_to "Edit", edit_article_path(article), class: "actions_edit" %>
      <%= link_to "Delete", article_path(article),  data:{ turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "actions_del" %>
    </div>
    <div class="card-footer text-white"  id="head_foot">
      Posted <%=  time_ago_in_words(article.created_at)%> ago... Updated <%=  time_ago_in_words(article.updated_at)%> ago...
    </div>
  </div>
  <% end %>

app/views/articles/_error.html.erb
<% if @article.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
<h3>The following errors prevented the article from being created!</h3>
<hr>
<ul>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
</ul>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/articles/_form.html.erb
<div class="art_box">
<%= form_with(model: @article,  local: true, data: { turbo: false })  do |f| %>
<div class="form_content">
<div class=" form-group row">
<%= f.label :title, class: "col-2 col-form-label" %>
<div class="col-10">
<%= f.text_field :title, class: "form-control rounded-1", placeholder: "Type in title" %>
</div>
</div>
<div  class="form-group row">
<%= f.label :description, class: "col-2 col-form-label" %><br/>
<div class="col-10  my-1">
<%= f.text_area :description, class: "form-control", placeholder: "Type in description" %>
</div>
<%= f.label :blog, class: "col-2 col-form-label" %><br/>
<div class="col-10">
<%= f.text_area :blog, rows: 10, class: "form-control", placeholder: "Type in article" %>
</div>
</div>
</div>
<div class="d-flex mt-3 align-items-start justify-content-between">
<%= link_to "Cancel", articles_path,  class: "btn btn-secondary" %>
<div>
</div>
<%= f.submit class: "btn btn-primary"%>
</div>
<% end %>
</div>


  

app/views/articles/edit.html.erb
<div class="container jumbotron">
<div class="new_art_box">
<div class="text-center">
<h2>Edit Article</h2>
</div>
<%= render "shared/errors", obj: @article %>
<%= render "form"%>
</div>
</div>

app/views/articles/index.html.erb
<div class="container mt-3 text-white">
<h2>Articles List</h2>
</div>
<div class="container jumbotron">
<div class="list_box">
<%= render 'article' %>
</div>
</div>
<div class="text-center mb-2">
<p><%= link_to "Create new article", new_article_path, class: "create" %></p>
</div>

app/views/articles/new.html.erb
<div class="container jumbotron">
<div class="new_art_box">
<div class="text-center">
<h2>Create a New Article</h2>
</div>
<%= render "shared/errors", obj: @article %>
<%= render "form"%>
</div>
</div>

app/views/articles/show.html.erb
<div class="container jumbotron">
<div class="new_art_box">
<div class="text-center">
<h2><%=@article.title.titlecase%></h2>
</div>
 <%= render "layouts/messages" %>
<div class="art_box">
<div class="art_content">
<p>
<strong>Title: </strong><%=@article.title.titlecase%><br/>
Created: <%= time_ago_in_words@article.created_at %> ago...
Updated: <%= time_ago_in_words@article.updated_at %> ago...
by <%= @article.user.first_name %>  <%= @article.user.last_name %>
</p>
<p><strong>Description: </strong><%=@article.description%></p>
<div>
<p><strong></strong><%=@article.blog%></p>
</div>
</div>
<div class="show_links_box mt-3">
<div>
<%= link_to "Return to List", articles_path, class: "show_links_go" %>
</div>
<div class="edit_del">
<%= link_to "Edit", edit_article_path(@article), class: "show_links_update" %>
<%= link_to "Delete", article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }, class: "show_links_del" %>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/_footer.html.erb
<div  id="page-content">
</div>
<footer id="sticky-footer" class="flex-shrink-0 py-3 bg-dark text-white-50">
<div class="container text-center">
  <small>Copyright &copy; 2024 ALPHA BLOG</small>
</div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %> 
  <div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= msg %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">ALPHA BLOG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(articles_path) %>" aria-current="page" href="/articles">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(articles_path) %>" aria-current="page" href="/users">Bloggers</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/articles/new">Create New Article</a></li>
            <li><a class="dropdown-item" href="/articles">View Articles</a></li>  
            <li><a class="dropdown-item" href="/signup">Sign up</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Log in</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(about_path) %>" aria-current="page" href="/about">About</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">  
    </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
     <%= render "layouts/footer" %> 
  </body>
</html>

app/views/pages/about.html.erb
<div class="container jumbotron">
<h2>About Page</h2>
<div class="art_box">
<div class="art_content">
<p>"Alpha Blog is a platform built for thinkers, creators, and storytellers who want to share their perspectives with the world. Whether you're passionate about writing, exploring new ideas, or connecting with a community of readers, Alpha Blog offers a space for your voice to be heard. Our mission is to empower individuals to express their creativity and engage in thoughtful conversations. With an intuitive interface and a welcoming environment, Alpha Blog makes it easy to dive into topics that matter and build connections that inspire."</p>
</div>
</div>
</div>

app/views/pages/index.html.erb
<div class="home_box container">
<div  class="greeting_box">
<div class="row">
<%= render "layouts/messages" %>
</div>

<div class="sub_home row">
<h1>Welcome to Alpha Blog</h1>
<p>"Where ideas come to life. Share your thoughts, explore diverse perspectives, and engage with a vibrant community of writers."</p>
<br/>
<p>"Whether you're here to share your insights, read compelling stories, or connect with like-minded individuals, Alpha Blog is the place for meaningful conversations and creative expression."</p>
<div>
<p><%= link_to "Sign up", signup_path, class: "signup" %></p>
</div>
</div>
</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
<h3>The following errors prevented the <%= obj.class.name.downcase %> from being created!</h3>
<hr>
<ul>
    <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
</ul>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="new_user_box">

        <%= form_with(model: @user,  local: true, data: { turbo: false })  do |f| %>
            <div  class="form_content justfy-contents-between">

                <div class="form-group row my-2 justify-content-between">
                    <%= f.label :first, class: "col-2 col-form-label" %>
                        <div class="col-8">
                            <%= f.text_field :first_name, class: "form-control rounded-1", placeholder: "Type in first name" %>
                        </div>
                </div>

                <div class="form-group row my-2 justify-content-between">
                    <%= f.label :last, class: "col-2 col-form-label" %>
                        <div class="col-8">
                            <%= f.text_field :last_name, class: "form-control rounded-1", placeholder: "Type in last name" %>
                        </div>
                </div>

                <div class="form-group row my-2 justify-content-between">
                    <%= f.label :email, class: "col-2 col-form-label" %>
                        <div class="col-8">
                            <%= f.email_field :email, class: "form-control rounded-1", placeholder: "Type in email" %>
                        </div>
                </div>

                <div class="form-group row my-2 justify-content-between">
                    <%= f.label :username, class: "col-2 col-form-label" %>
                        <div class="col-8">
                            <%= f.text_field :username, class: "form-control rounded-1", placeholder: "Type in username" %>
                        </div>
                </div>

                <div class="form-group row my-2 justify-content-between">
                    <%= f.label :password, class: "col-2 col-form-label" %>
                        <div class="col-8">
                            <%= f.password_field :password, class: "form-control rounded-1", placeholder: "Type in password" %>
                        </div>
                </div>

            </div>

            <div  class="d-flex mt-3 align-items-start justify-content-between">
                <%= link_to "Cancel", root_path,  class: "btn btn-secondary" %>
                <%= f.submit class: "btn btn-primary"  %>
            </div>

            

    <% end %>
</div>

app/views/users/_userList.html.erb
<% @users.each do |user| %>
<div class="card mb-3" style="max-width: 540px;">
  <div class="row d-flex justify-content-between">
    <div class="col-md-3 d-flex align-item-center">
      <%= gravatar_for(user, size: 150)%>
    </div>
    <div class="col-md-8 px-3">
      <div class="card-body">
        <h5 class="card-title"><%= user.first_name%> <%= user.last_name%></h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-body-secondary">Member since:  <%=  time_ago_in_words(user.created_at)%> ago</small></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="container jumbotron">
<div class="new_art_box">
<div class="text-center">
<h2>User Profile Update</h2>
</div>
<%= render "shared/errors", obj: @user %>
<%= render "form" %>
</div>
</div>

app/views/users/index.html.erb
<div class="text-center container jumbotron">
<h4>Bloggers</h4>
<div class="text-center position-absolute">

</div>
<div class="bloggers">
<div class="text-center">
</div>
<%= render "userList" %>
</div>

</div>
</div>

app/views/users/new.html.erb
<div class="container jumbotron">
<div class="new_art_box">
<div class="text-center">
<h2>Sign up for Alpha Blog</h2>
</div>
<%= render "shared/errors", obj: @user %>
<%= render "form" %>
</div>
</div>

app/views/users/show.html.erb
<div class="container jumbotron">
<div class="new_art_box">
<div class="text-center">
<%= gravatar_for @user %>
<h3><%= @user.username %>'s Articles</h3>
</div>
<%= render "articles/article" %>
</div>
</div>